### ISSUE TITLE
Not syncing in Gulp

### ISSUE THREAD

**Issue by bakura10** [panoply/shopify-sync#5]
Hi,

First of all thanks for this great little library.

I'm however encountering an issue that prevent me from using it. I've realized that if I directly edit a file that is part of the "dist" folder, this library will properly sync it to Shopify.

However, if the file within the dist folder is replaced as a result of another gulp task (for instance a gulp task is watching the "css" folder and copying the generated CSS to the "/dist/assets" folder, then this file is not sync most of the time (it is only sync one every 30 or 40 changes).

I'm not sure why but the library is not being able to properly watch every changes.

**Comment by panoply** [comment]
Hey @bakura10 

Can you maybe create a gist of your Gulp workflow? I'd say this issue is something unrelated to this project but more so related to the plugins that are generating the CSS as I believe in the past I've had similar issues in that nexus. 

You can look at a strap I've published for Shopify theme bundling which uses this module maybe you can take something from that or at the very least it will help you: 

https://github.com/panoply/straps/blob/master/shopify-starter/bundle/styles.js

**Comment by bakura10** [comment]
Hi,

I've did a bit more testing with another library I used (https://www.npmjs.com/package/gulp-shopify-upload) and it's not working neither, so the issue is not yours, sorry for the false alert.

The difference between my new project and the old one (where the previous gulp package was working) was that I use gulp 4 now instead of 3, so I suppose the issue is coming to how Gulp 4 is working internally.

**Comment by panoply** [comment]
Glad you could work it out and get to the bottom of the issue. Thanks for leaving some additional context as to what was causing the issue. Best of luck on your project.
